### ISSUE TITLE
Dialog being read twice

### ISSUE THREAD

**Issue by Citrus333** [karashiiro/TextToTalk#136]
Each dialog is being read by TTT twice, didn't happen yesterday, perhaps a small glitch that isn't consistent.

**Comment by johnysandels** [comment]
That typically happens when you have NPC dialogue checked in channel settings tab in the plugin settings.
Try turning unchecking that box and see if that helps. This is usually caused by the plugin reading dialogue posted in the chat and also reading the on screen dialogue box.

**Comment by karashiiro** [comment]
Has that always happened? It's supposed to track the last NPC text so that the chat handler can skip it.

**Comment by johnysandels** [comment]
It's been around as long as I can remember. I assume the chat handler has been catching most of them, but they must make it through sometimes. 
Maybe differences of punctuations, or text continuing on a second text box.

**Comment by karashiiro** [comment]
I got a separate bug report about this in Discord saying the same thing, but it should have been fixed ever since #40 was closed. I thought this was something new 😵‍💫

**Comment by Citrus333** [comment]
TBH I used the addon for a few weeks without it happening, updated to the newest version, didn't change any settings, and it started doing it.  Even with 'cancel voice if new lines start' enabled it still happens, I can cancel the dialog and sometimes still get double voice.

**Comment by johnysandels** [comment]
And that option I mentioned earlier was already unselected?

**Comment by ABlingManPlays** [comment]
I am having the same problem with some of my text, specifically green NPC dialogue in combat instances. My friend was helping me go through the settings and I found multiple instances of the NPC Dialogue option checked. If I uncheck the top one, the bottom one also unchecks. If I try to uncheck the bottom one, nothing happens. There are also multiple instances of NPC Announcement in that list. If I click on either instance of NPC Announcement, both toggle.
![ffxiv_08202023_041729_665](https://github.com/karashiiro/TextToTalk/assets/142716429/85aa89ef-d5ee-4a21-9d8e-ae28e33c579d)
![ffxiv_08202023_042342_381](https://github.com/karashiiro/TextToTalk/assets/142716429/2c9e80b6-0ecb-419c-93ba-1bff28f16ea6)

**Comment by karashiiro** [comment]
The duplicate options are fixed in the testing versions I think, that's just because Dalamud added them at some point and TTT combines that with its own list. That part shouldn't be causing issues since the settings are synchronized.
